import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Dil türleri
export type Language = 'tr' | 'en';

// Dil context interface'i
interface LanguageContextType {
  currentLanguage: Language;
  changeLanguage: (language: Language) => Promise<void>;
  t: (key: string) => string; // Çeviri fonksiyonu
}

// Dil context'i oluştur
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Çeviri anahtarları
const translations = {
  tr: {
    // Ana Sayfa
    'home.title': 'Ana Sayfa',
    'home.findMatch': 'Maç Bul',
    'home.createMatch': 'Maç Oluştur',
    'home.myMatches': 'Maçlarım',
    'home.otherMatches': 'Diğer Maçlar',
    'home.noMatchesFound': 'Maç bulunamadı',
    'home.loading': 'Yükleniyor...',
    'home.refresh': 'Yenile',
    'home.matchDetails': 'Maç Detayları',
    'home.matchTitle': 'Maç Başlığı',
    'home.matchDate': 'Tarih',
    'home.matchTime': 'Saat',
    'home.matchLocation': 'Konum',
    'home.matchPrice': 'Fiyat',
    'home.matchPlayers': 'Oyuncular',
    'home.joinMatch': 'Maça Katıl',
    'home.leaveMatch': 'Maçtan Ayrıl',
    'home.matchFull': 'Maç Dolu',
    'home.matchCancelled': 'Maç İptal',
    'home.condition': 'KONDİSYONUN',
    'home.conditionNeed3Matches': 'Kondisyon kazanman için en az 3 maç yapman lazım!',
    'home.conditionNextMatch80': 'Eğer 1 maç daha yaparsan kondisyonun 80\'e yükselecek',
    'home.conditionNextMatch90': 'Eğer 1 maç daha yaparsan kondisyonun 90\'a yükselecek',
    'home.conditionFirst5Complete': 'İlk 5 maçını tamamladın. Spor yapmaya devam ☺️',
    'home.conditionAchieved': 'Gerekli kondisyonu kazandın. Sağlıklı günler 👏',
    'home.matchSummary': 'MAÇ ÖZETİ',
    'home.missingSquads': 'Eksik Mevkiler',
    'home.matchCreatedBy': 'Maçı oluşturan:',
    'home.pitchSummary': 'HALI SAHA ÖZETİ',
    'home.openAddress': 'Açık Adres',
    'home.pitchPrice': 'Saha Ücreti',
    'home.pitchFeatures': 'Sahanın Özellikleri',
    'home.matchPlaying': 'Maç oynanıyor',
    'home.waitingMatches': 'SENİ BEKLEYEN MAÇLAR',
    'home.noMatchesCreated': 'Oluşturduğun Maç Yok!',
    'home.createMatchNow': 'Hemen Maç Oluştur',
    'home.matchesLoading': 'Maç Listesi Yükleniyor..',
    'home.incompleteSquadMatches': 'KADROSU EKSİK MAÇLAR',
    'home.noIncompleteSquadMatches': 'Başkaları Tarafından Oluşturulan Kadrosu Eksik Maç Yok!',
    
    // Profil
    'profile.title': 'Profil',
    'profile.settings': 'Ayarlar',
    'profile.logout': 'Çıkış Yap',
    'profile.editProfile': 'Kişisel Bilgilerini Tamamla',
    'profile.name': 'Adınız',
    'profile.surname': 'Soyadınız',
    'profile.age': 'Yaş',
    'profile.height': 'Boy',
    'profile.weight': 'Kilo',
    'profile.description': 'Mevki / Biyografi',
    'profile.save': 'Kaydet',
    'profile.cancel': 'İptal Et',
    'profile.followers': 'Takipçi',
    'profile.following': 'Takip',
    'profile.follow': 'Takip Et',
    'profile.followingYou': 'Seni takip ediyor',
    'profile.youFollowing': 'Takip ediyorsun',
    'profile.profileImage': 'Profil Fotoğrafı',
    'profile.changePhoto': 'Fotoğraf Değiştir',
    'profile.personalInfo': 'Kişisel Bilgiler',
    'profile.profileUpdated': 'Profil güncellendi',
    'profile.updateError': 'Profil güncellenirken hata oluştu',
    'profile.logoutError': 'Çıkış yapılamadı',
    'profile.logoutErrorMsg': 'Bir hata oluştu',
    'profile.noFollowersYet': 'Henüz takipçi yok',
    'profile.followRequestSent': 'Takip isteğin gönderildi',
    'profile.userSessionNotFound': 'Kullanıcı oturumu bulunamadı',
    'profile.ownUserDataNotFound': 'Kendi kullanıcı bilgilerin alınamadı',
    'profile.unfollowed': 'Takipten çıkıldı',
    'profile.unfollowError': 'Takipten çıkılırken bir hata oluştu. Lütfen tekrar deneyin.',
    'profile.followRequestError': 'Takip isteği gönderilirken bir hata oluştu. Lütfen tekrar deneyin.',
    'profile.alreadyFollowingOrRequested': 'Zaten takip isteği gönderdiniz veya takip ediyorsunuz.',
    'profile.followRequestSentSuccess': 'Takip isteği gönderildi',
    'profile.noDescription': 'Açıklama Yok',
    'profile.noName': 'İsim Yok',
    'profile.editProfileInfo': 'Profil Bilgilerimi Düzenle',
    'profile.completePersonalInfo': 'Kişisel Bilgilerini Tamamla',
    'profile.position': 'Mevki',
    'profile.field.name': 'Ad',
    'profile.field.surname': 'Soyad',
    'profile.field.age': 'Yaş',
    'profile.field.height': 'Boy',
    'profile.field.weight': 'Kilo',
    'profile.field.position': 'Mevki',
    'profile.myMatches': 'MAÇLARIM',
    'profile.matches': 'Maç',
    'profile.condition': 'KONDİSYONUN',
    'profile.conditionNeed3Matches': 'Kondisyon kazanman için en az 3 maç yapman lazım!',
    'profile.conditionNextMatch80': 'Eğer 1 maç daha yaparsan kondisyonun 80\'e yükselecek',
    'profile.conditionNextMatch90': 'Eğer 1 maç daha yaparsan kondisyonun 90\'a yükselecek',
    'profile.conditionFirst5Complete': 'İlk 5 maçını tamamladın. Spor yapmaya devam ☺️',
    'profile.conditionAchieved': 'Gerekli kondisyonu kazandın. Sağlıklı günler 👏',
    'profile.notFollowingAnyoneYet': 'Henüz kimseyi takip etmiyor',
    
    // ProfilePreview için ek çeviriler
    'profilePreview.title': 'Profil Önizleme',
    'profilePreview.close': 'Kapat',
    'profilePreview.viewProfile': 'Profili Görüntüle',
    'profilePreview.followUser': 'Kullanıcıyı Takip Et',
    'profilePreview.unfollowUser': 'Takipten Çık',
    'profilePreview.followRequestPending': 'Takip İsteği Beklemede',
    'profilePreview.followRequestAccepted': 'Takip İsteği Kabul Edildi',
    'profilePreview.followRequestRejected': 'Takip İsteği Reddedildi',
    'profilePreview.mutualFollow': 'Karşılıklı Takip',
    'profilePreview.youFollowThem': 'Onları Takip Ediyorsun',
    'profilePreview.theyFollowYou': 'Seni Takip Ediyor',
    'profilePreview.noMutualFollow': 'Karşılıklı Takip Yok',
    'profilePreview.profileImage': 'Profil Resmi',
    'profilePreview.viewImage': 'Resmi Görüntüle',
    'profilePreview.closeImage': 'Resmi Kapat',
    'profilePreview.following': 'Takip',
    'profilePreview.youAreFollowing': 'Takip ediyorsun',
    'units.cm': 'cm',
    'units.kg': 'kg',
    
    // Maç Oluştur
    'create.title': 'Maç Oluştur',
    'create.matchTitle': 'Maç Başlığı',
    'create.matchTitlePlaceholder': 'Maç Başlığı Giriniz',
    'create.location': 'Saha Seç',
    'create.selectDistrict': 'İlçe Seçiniz',
    'create.selectPitch': 'Halı Saha Seçiniz',
    'create.price': 'Fiyat',
    'create.pricePlaceholder': 'Halı Sahanın Fiyatı',
    'create.dateTime': 'Tarih ve Saat',
    'create.createMatch': 'Maç Oluştur',
    'create.squadIncomplete': 'Kadro Eksik mi?',
    'create.selectMissingPositions': 'Eksik Mevkileri Seçin',
    'create.goalkeeper': 'Kaleci',
    'create.defender': 'Defans',
    'create.midfielder': 'Orta Saha',
    'create.forward': 'Forvet',
    'create.howManyMissing': 'Kaç {position} eksik?',
    'create.selectDistrictPlaceholder': 'İlçe Seçiniz',
    'create.selectPitchPlaceholder': 'Halı Saha Seçiniz',
    'create.squadIncompleteQuestion': 'Kadro Eksik mi?',
    'create.selectMissingPositionsTitle': 'Eksik Mevkileri Seçin',
    'create.howManyMissingQuestion': 'Kaç {position} eksik?',
    'create.goalkeeperShort': 'K',
    'create.defenderShort': 'D',
    'create.midfielderShort': 'O',
    'create.forwardShort': 'F',
    'create.locationTitle': 'Saha Seç',
    'create.districtTitle': 'İlçe',
    'create.pitchTitle': 'Halı Saha',
    'create.priceTitle': 'Fiyat',
    'create.dateTimeTitle': 'Tarih ve Saat',
    'create.dateTitle': 'Tarih',
    'create.timeTitle': 'Saat',
    'create.selectDatePlaceholder': 'Tarih Seçiniz',
    'create.selectTimePlaceholder': 'Saat Seçiniz',
    'create.morning': 'Sabah',
    'create.afternoon': 'Öğleden Sonra',
    'create.evening': 'Akşam',
    'create.night': 'Gece',

    // Create - Reservation Warning Modal
    'create.reservationWarning.alertTitle': 'Uyarı',
    'create.reservationWarning.alertMessage': 'Lütfen önce saha rezervasyonu yaptığınızı onaylayın.',
    'create.reservationWarning.title': '⚠️ ÖNEMLİ UYARI',
    'create.reservationWarning.reservationTitle': '📞 Saha Rezervasyonu',
    'create.reservationWarning.reservationTextPrefix': 'Maç oluşturmadan önce',
    'create.reservationWarning.reservationTextEmphasis': 'mutlaka',
    'create.reservationWarning.reservationTextSuffix': 'sahanın telefon numarasını arayarak rezervasyon yapmanız gerekmektedir.',
    'create.reservationWarning.createTitle': '⚽ Maç Oluşturma',
    'create.reservationWarning.createText': 'Rezervasyon yaptıktan sonra maçınızı oluşturabilir ve eksik pozisyonları belirleyebilirsiniz.',
    'create.reservationWarning.checkboxText': 'Öncelikle Sahayı Rezerve Et ardından Maçı Oluştur',
    
    // Halı Sahalar
    'pitches.title': 'Sahalar',
    'pitches.selectDistrict': 'İlçe Seçiniz',
    'pitches.selectPitch': 'Halı Saha Seçiniz',
    'pitches.noPitchesFound': 'Bu ilçede halı saha bulunamadı',
    'pitches.selectDistrictFirst': 'Önce ilçe seçiniz',
    'pitches.pitchPrice': 'Saha Ücreti',
    'pitches.selectPitchFirst': 'Önce halı saha seçiniz',
    'pitches.locationPermissionRequired': 'Konum izni gerekli',
    'pitches.locationPermissionMessage': 'Uygulamayı kullanmak için konum izni vermeniz gerekiyor.',
    'pitches.addressNotFound': 'Adres bulunamadı.',
    'pitches.addressCouldNotBeRetrieved': 'Adres alınamadı.',
    'pitches.locationCouldNotBeRetrieved': 'Konum alınamadı.',
    'pitches.locationError': 'Konum Hatası',
    'pitches.locationInfoCouldNotBeRetrieved': 'Konum bilgisi alınamadı.',
    'pitches.permissionCheckError': 'İzin kontrolünde hata',
    'pitches.dataFetchError': 'Veri çekme hatası',
    'pitches.listPitchesByLocation': 'Konumuna Göre Halı Sahaları Listele',
    'pitches.yourAddress': 'Adresin',
    'pitches.findYourLocation': 'Konumunu Bul',
    'pitches.pitchSummary': 'HALI SAHA ÖZETİ',
    'pitches.openAddress': 'Açık Adres',
    'pitches.pitchFeatures': 'Sahanın Özellikleri',
    
    // Mesajlar
    'messages.title': 'Mesajlar',
    'messages.noAcceptedJoins': 'Henüz katıldığın maç yok',
    
    // Bildirimler
    'notifications.title': 'Bildirimler',
    'notifications.loadingError': 'Bildirimler yüklenirken hata',
    'notifications.followRequestError': 'Takip isteği işlenirken hata',
    'notifications.sentFollowRequest': 'sana takip isteği gönderdi.',
    'notifications.sentMessage': 'size mesaj gönderdi.',
    'notifications.noNotificationsYet': 'Henüz bildiriminiz yok',
    'notifications.userFallback': 'Kullanıcı',
    'notifications.toast.accepted': 'İstek kabul edildi',
    'notifications.toast.rejected': 'İstek reddedildi',
    'notifications.actionCompleted': 'İşlem tamamlandı',

    // Takip isteği geri bildirimleri (follow_request) - sadece bunun EN çevirisini kullanacağız
    'notifications.follow.startedFollowing': '{name} seni takip etmeye başladı.',
    'notifications.follow.acceptedYourRequest': '{name} takip isteğinizi kabul etti.',
    'notifications.follow.rejectedYourRequest': '{name} takip isteğinizi reddetti.',
    'notifications.follow.youRejectedRequest': '{name} kullanıcısının takip isteğini reddettiniz.',
    
    // Genel
    'general.close': 'Kapat',
    'general.cancel': 'İptal',
    'general.save': 'Kaydet',
    'general.edit': 'Düzenle',
    'general.delete': 'Sil',
    'general.yes': 'Evet',
    'general.no': 'Hayır',
    'general.ok': 'Tamam',
    'general.error': 'Hata',
    'general.success': 'Başarılı',
    'general.loading': 'Yükleniyor...',
    'general.back': 'Geri dön',
    'general.notifications': 'Bildirimler',
    'general.notificationCount': 'Bildirim Sayısı',
    'general.reject': 'Reddet',
    'general.accept': 'Kabul Et',
    'general.sendMessage': 'Mesaj Gönder',
    
    // Dil Ayarları
    'language.settings': 'Dil Ayarları',
    'language.turkish': 'Türkçe',
    'language.english': 'İngilizce',
    'language.changed': 'Dil değiştirildi',
    'language.changedToTurkish': 'Dil Türkçe olarak ayarlandı',
    'language.changedToEnglish': 'Language set to English',
    'language.changeFailed': 'Dil değiştirilemedi',

    // Settings Modal
    'settings.invalidEmail': 'Lütfen geçerli bir e-posta adresi girin.',
    'settings.emailUpdateRequestedVerifyInbox': 'E-posta değişikliği isteği alındı. Lütfen gelen kutunu kontrol edip doğrulama adımını tamamla.',
    'settings.emailUpdatedMaybeVerify': 'E-posta güncellendi. Eğer doğrulama gerekiyorsa e-posta gönderilmiş olabilir.',
    'settings.emailUpdateFailed': 'E-posta güncellenemedi. Lütfen tekrar deneyin.',
    'settings.passwordMin': 'Şifre en az 6 karakter olmalı.',
    'settings.passwordsMismatch': 'Şifreler eşleşmiyor.',
    'settings.passwordUpdated': 'Şifre güncellendi.',
    'settings.passwordUpdateFailed': 'Şifre güncellenemedi. Lütfen tekrar deneyin.',
    'settings.accountDeleted': 'Hesabınız silindi.',
    'settings.accountDeleteFailed': 'Hesap silinemedi. Lütfen tekrar deneyin veya destek ile iletişime geçin.',

    'settings.delete.title': 'Hesabı Sil',
    'settings.delete.description': 'Hesabınızı sildiğiniz taktirde profiliniz, mesajlarınız, bildirimleriniz ve diğer verileriniz kalıcı olarak silinecektir.',
    'settings.delete.irreversible': 'Bu işlem geri alınamaz.',
    'settings.delete.confirmQuestion': 'Devam etmek istiyor musunuz?',
    'settings.delete.confirmButton': 'Evet sil',

    'settings.account.title': 'Hesap Bilgilerim',
    'settings.account.emailLabel': 'E-posta',
    'settings.account.passwordLabel': 'Şifre',
    'settings.account.passwordHiddenNote': 'Şifre güvenlik nedeniyle gösterilmez.',
    'settings.account.updateEmail': 'E-postayı Güncelle',
    'settings.account.changePassword': 'Şifreyi Değiştir',
    'settings.account.newEmailLabel': 'Yeni E-posta',
    'settings.account.emailPlaceholder': 'ornek@mail.com',
    'settings.account.emailVerifyNote': 'Not: E-posta değişimi için doğrulama maili gerekebilir.',
    'settings.account.newPasswordLabel': 'Yeni Şifre',
    'settings.account.newPasswordConfirmLabel': 'Yeni Şifre (Tekrar)',

    'settings.device.title': 'Cihaz Bilgileri',
    'settings.device.appInfoTitle': 'Uygulama Bilgileri',
    'settings.device.appLabel': 'Uygulama',
    'settings.device.versionLabel': 'Sürüm',
    'settings.device.deviceLabel': 'Cihaz',
    'settings.device.osLabel': 'İşletim Sistemi',
    'settings.device.updateStatusLabel': 'Güncelleme Durumu',
    'settings.device.updateNotSupported': 'Bu cihazda kontrol edilemiyor',
    'settings.device.updateChecking': 'Kontrol ediliyor...',
    'settings.device.updateCheckFailed': 'Kontrol edilemedi',
    'settings.device.updateAvailable': 'Güncelleme var',
    'settings.device.upToDate': 'Güncel',
    'settings.device.unknown': 'Bilinmiyor',
    'settings.device.goToStore': 'App Store’a Git',

    // Auth (Giriş / Kayıt)
    'auth.slide1.title': 'Maç Bul',
    'auth.slide1.subtitle': 'Yakınındaki maçlara katıl, yeni insanlarla oyna.',
    'auth.slide2.title': 'Maç Oluştur',
    'auth.slide2.subtitle': 'Sahanı seç, saati belirle, ekibini kur.',
    'auth.slide3.title': 'Kadronu Yönet',
    'auth.slide3.subtitle': 'Eksik pozisyonları belirle, talepleri yönet.',
    'auth.slide4.title': 'Mesajlaş',
    'auth.slide4.subtitle': 'Takım arkadaşlarınla ve rakiplerinle sohbet et.',
    'auth.slide5.title': 'Profilini Doldur',
    'auth.slide5.subtitle': 'Kendini tanıt, daha iyi eşleşmeler yakala.',
    'auth.slide6.title': 'Profilini Doldur',
    'auth.slide6.subtitle': 'Kendini tanıt, daha iyi eşleşmeler yakala.',

    'auth.welcomeTitle': 'Hoş Geldin',
    'auth.joinTitle': 'Aramıza Katıl!',
    'auth.brand': 'S A H A Y A B A K',
    'auth.subtitleLoginPrefix': 'Sahaya çıkmak için',
    'auth.subtitleLoginAction': 'giriş yap',
    'auth.subtitleSignup': 'Yeni bir hesap oluştur',

    'auth.emailPlaceholder': 'E-posta adresin',
    'auth.passwordPlaceholder': 'Şifren',
    'auth.signInButton': 'Giriş Yap',
    'auth.signUpButton': 'Kayıt Ol',

    'auth.noAccountQuestion': 'Hesabın yok mu?',
    'auth.signUpLink': 'Kayıt ol',
    'auth.haveAccountQuestion': 'Zaten hesabın var mı?',
    'auth.signInLink': 'Giriş yap',
    'auth.or': 'veya',
    'auth.googleSignIn': 'Google Hesabıyla Giriş Yap',
    'auth.appleSignIn': 'Apple Hesabınla Giriş Yap',
    'auth.completeProfileNote': 'Giriş yaptıktan sonra profil bilgilerini tamamlayabilirsin.',

    'auth.userCreateFailed': 'Kullanıcı kaydı oluşturulamadı. Lütfen tekrar deneyin.',
    'auth.unknownError': 'Bilinmeyen hata',
    'auth.fillAllFields': 'Lütfen tüm alanları doldurun.',
    'auth.invalidEmail': 'Geçersiz e-posta formatı.',
    'auth.passwordMin': 'Şifre en az 6 karakter olmalıdır.',
    'auth.signupSuccessVerifyEmail': 'Kayıt başarılı! E-postanızı doğrulamanız gerekmektedir. E-postanızı kontrol ederek mail adresinizi doğrulayınız!',
    'auth.signInCancelled': 'Giriş iptal edildi.',
    'auth.userInfoMissing': 'Kullanıcı bilgisi alınamadı.',
    'auth.appleAuthFailed': 'Apple kimlik doğrulama başarısız (token alınamadı).',

    'auth.errors.passwordMin': 'Şifre en az 6 karakter olmalıdır.',
    'auth.errors.invalidEmail': 'Geçersiz e-posta formatı.',
    'auth.errors.userAlreadyRegistered': 'Bu e-posta ile kayıtlı bir kullanıcı zaten var.',
    'auth.errors.userAlreadyExists': 'Bu e-posta adresiyle bir hesap zaten var.',
    'auth.errors.invalidCredentials': 'E-posta veya şifre hatalı.',
    'auth.errors.emailNotConfirmed': 'E-posta adresinizi doğrulamanız gerekiyor.',
    'auth.errors.userNotFound': 'Kullanıcı bulunamadı.',
    'auth.errors.appleMissingOAuthSecret': "Apple ile giriş için Supabase'de Apple OAuth ayarlarında 'Client secret' eksik. Supabase Dashboard → Auth → Providers → Apple kısmına Services ID ve Secret girmeniz gerekiyor.",
    'auth.errors.missingOAuthSecret': 'OAuth için gerekli secret eksik. Supabase Dashboard → Auth → Providers kısmında ilgili sağlayıcı için Client secret tanımlayın.',
    
    // Maç
    'match.createSuccess': 'Tebrikler 🎉\nMaçınız başarılı bir şekilde oluşturulmuştur.',
    'match.createError': 'Maç oluşturulurken bir hata oluştu. Lütfen tekrar deneyin.',
    'match.title': 'Maç Başlığı',
    'match.date': 'Tarih',
    'match.time': 'Saat',
    'match.location': 'Konum',
    'match.price': 'Fiyat',
    'match.players': 'Oyuncular',
    'match.selectDate': 'Tarih Seçin',
    'match.selectTime': 'Saat Seçin',
    'match.today': 'Bugün',
    'match.tomorrow': 'Yarın',
    'match.thisWeek': 'Bu Hafta',
    'match.nextWeek': 'Gelecek Hafta',
    'match.morning': 'Sabah',
    'match.afternoon': 'Öğleden Sonra',
    'match.evening': 'Akşam',
    'match.night': 'Gece',
    'dateFormat.day': 'Gün',
    'dateFormat.month': 'Ay',
    'dateFormat.year': 'Yıl',
    'dateFormat.today': 'Bugün',
    'dateFormat.tomorrow': 'Yarın',
    'dateFormat.thisWeek': 'Bu Hafta',
    'dateFormat.nextWeek': 'Gelecek Hafta',
  },
  
  en: {
    // Home
    'home.title': 'Home',
    'home.findMatch': 'Find',
    'home.createMatch': 'Create Match',
    'home.myMatches': 'My Matches',
    'home.otherMatches': 'Other Matches',
    'home.noMatchesFound': 'No matches found',
    'home.loading': 'Loading...',
    'home.refresh': 'Refresh',
    'home.matchDetails': 'Match Details',
    'home.matchTitle': 'Match Title',
    'home.matchDate': 'Date',
    'home.matchTime': 'Time',
    'home.matchLocation': 'Location',
    'home.matchPrice': 'Price',
    'home.matchPlayers': 'Players',
    'home.joinMatch': 'Join Match',
    'home.leaveMatch': 'Leave Match',
    'home.matchFull': 'Match Full',
    'home.matchCancelled': 'Match Cancelled',
    'home.condition': 'CONDITION',
    'home.conditionNeed3Matches': 'You need to play at least 3 matches to gain condition!',
    'home.conditionNextMatch80': 'If you play 1 more match, your condition will rise to 80',
    'home.conditionNextMatch90': 'If you play 1 more match, your condition will rise to 90',
    'home.conditionFirst5Complete': 'You completed your first 5 matches. Keep exercising ☺️',
    'home.conditionAchieved': 'You have achieved the required condition. Healthy days 👏',
    'home.matchSummary': 'MATCH SUMMARY',
    'home.missingSquads': 'Missing Squads',
    'home.matchCreatedBy': 'Match created by:',
    'home.pitchSummary': 'PITCH SUMMARY',
    'home.openAddress': 'Open Address',
    'home.pitchPrice': 'Pitch Price',
    'home.pitchFeatures': 'Pitch Features',
    'home.matchPlaying': 'Match Playing',
    'home.waitingMatches': 'MATCHES WAITING FOR YOU',
    'home.noMatchesCreated': 'No Matches Created!',
    'home.createMatchNow': 'Create Match Now',
    'home.matchesLoading': 'Matches Loading..',
    'home.incompleteSquadMatches': 'INCOMPLETE SQUAD MATCHES',
    'home.noIncompleteSquadMatches': 'No Incomplete Squad Matches Created by Others!',
    
    // Profile
    'profile.title': 'Profile',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',
    'profile.editProfile': 'Complete Personal Information',
    'profile.name': 'Your Name',
    'profile.surname': 'Your Surname',
    'profile.age': 'Age',
    'profile.height': 'Height',
    'profile.weight': 'Weight',
    'profile.description': 'Position / Biography',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    'profile.follow': 'Follow',
    'profile.followingYou': 'Following you',
    'profile.youFollowing': 'You are following',
    'profile.profileImage': 'Profile Image',
    'profile.changePhoto': 'Change Photo',
    'profile.personalInfo': 'Personal Information',
    'profile.profileUpdated': 'Profile updated',
    'profile.updateError': 'Error updating profile',
    'profile.logoutError': 'Logout failed',
    'profile.logoutErrorMsg': 'An error occurred',
    'profile.noFollowersYet': 'No followers yet',
    'profile.followRequestSent': 'Follow request sent',
    'profile.userSessionNotFound': 'User session not found',
    'profile.ownUserDataNotFound': 'Your own user data could not be retrieved',
    'profile.unfollowed': 'Unfollowed',
    'profile.unfollowError': 'An error occurred while unfollowing. Please try again.',
    'profile.followRequestError': 'An error occurred while sending follow request. Please try again.',
    'profile.alreadyFollowingOrRequested': 'You have already sent a follow request or are following.',
    'profile.followRequestSentSuccess': 'Follow request sent',
    'profile.noDescription': 'No Description',
    'profile.noName': 'No Name',
    'profile.editProfileInfo': 'Edit My Profile Info',
    'profile.completePersonalInfo': 'Complete Your Personal Information',
    'profile.position': 'Position',
    'profile.field.name': 'Name',
    'profile.field.surname': 'Surname',
    'profile.field.age': 'Age',
    'profile.field.height': 'Height',
    'profile.field.weight': 'Weight',
    'profile.field.position': 'Position',
    'profile.myMatches': 'MY MATCHES',
    'profile.matches': 'Matches',
    'profile.condition': 'CONDITION',
    'profile.conditionNeed3Matches': 'You need to play at least 3 matches to gain condition!',
    'profile.conditionNextMatch80': 'If you play 1 more match, your condition will rise to 80',
    'profile.conditionNextMatch90': 'If you play 1 more match, your condition will rise to 90',
    'profile.conditionFirst5Complete': 'You completed your first 5 matches. Keep exercising ☺️',
    'profile.conditionAchieved': 'You have gained the necessary condition. Healthy days 👏',
    'profile.notFollowingAnyoneYet': 'Not following anyone yet',
    
    // ProfilePreview additional translations
    'profilePreview.title': 'Profile Preview',
    'profilePreview.close': 'Close',
    'profilePreview.viewProfile': 'View Profile',
    'profilePreview.followUser': 'Follow User',
    'profilePreview.unfollowUser': 'Unfollow User',
    'profilePreview.followRequestPending': 'Follow Request Pending',
    'profilePreview.followRequestAccepted': 'Follow Request Accepted',
    'profilePreview.followRequestRejected': 'Follow Request Rejected',
    'profilePreview.mutualFollow': 'Mutual Follow',
    'profilePreview.youFollowThem': 'You Follow Them',
    'profilePreview.theyFollowYou': 'They Follow You',
    'profilePreview.noMutualFollow': 'No Mutual Follow',
    'profilePreview.profileImage': 'Profile Image',
    'profilePreview.viewImage': 'View Image',
    'profilePreview.closeImage': 'Close Image',
    'profilePreview.following': 'Following',
    'profilePreview.youAreFollowing': 'You are following',
    'units.cm': 'cm',
    'units.kg': 'kg',
    
    // Create Match
    'create.title': 'Create',
    'create.matchTitle': 'Match Title',
    'create.matchTitlePlaceholder': 'Enter Match Title',
    'create.location': 'Select Pitch',
    'create.selectDistrict': 'Select District',
    'create.selectPitch': 'Select Pitch',
    'create.price': 'Price',
    'create.pricePlaceholder': 'Pitch Price',
    'create.dateTime': 'Date and Time',
    'create.createMatch': 'Create Match',
    'create.squadIncomplete': 'Is Squad Incomplete?',
    'create.selectMissingPositions': 'Select Missing Positions',
    'create.goalkeeper': 'Goalkeeper',
    'create.defender': 'Defender',
    'create.midfielder': 'Midfielder',
    'create.forward': 'Forward',
    'create.howManyMissing': 'How many {position} missing?',
    'create.selectDistrictPlaceholder': 'Select District',
    'create.selectPitchPlaceholder': 'Select Pitch',
    'create.squadIncompleteQuestion': 'Is Squad Incomplete?',
    'create.selectMissingPositionsTitle': 'Select Missing Positions',
    'create.howManyMissingQuestion': 'How many {position} missing?',
    'create.goalkeeperShort': 'G',
    'create.defenderShort': 'D',
    'create.midfielderShort': 'M',
    'create.forwardShort': 'F',
    'create.locationTitle': 'Select Pitch',
    'create.districtTitle': 'District',
    'create.pitchTitle': 'Pitch',
    'create.priceTitle': 'Price',
    'create.dateTimeTitle': 'Date and Time',
    'create.dateTitle': 'Date',
    'create.timeTitle': 'Time',
    'create.selectDatePlaceholder': 'Select Date',
    'create.selectTimePlaceholder': 'Select Time',
    'create.morning': 'Morning',
    'create.afternoon': 'Afternoon',
    'create.evening': 'Evening',
    'create.night': 'Night',

    // Create - Reservation Warning Modal
    'create.reservationWarning.alertTitle': 'Warning',
    'create.reservationWarning.alertMessage': 'Please confirm that you have reserved the pitch first.',
    'create.reservationWarning.title': '⚠️ IMPORTANT WARNING',
    'create.reservationWarning.reservationTitle': '📞 Pitch Reservation',
    'create.reservationWarning.reservationTextPrefix': 'Before creating a match, you must',
    'create.reservationWarning.reservationTextEmphasis': 'always',
    'create.reservationWarning.reservationTextSuffix': 'call the pitch phone number and make a reservation.',
    'create.reservationWarning.createTitle': '⚽ Creating a Match',
    'create.reservationWarning.createText': 'After reserving, you can create your match and select missing positions.',
    'create.reservationWarning.checkboxText': 'Reserve the Pitch first, then Create the Match',
    
    // Pitches
    'pitches.title': 'Pitches',
    'pitches.selectDistrict': 'Select District',
    'pitches.selectPitch': 'Select Pitch',
    'pitches.noPitchesFound': 'No pitches found in this district',
    'pitches.selectDistrictFirst': 'Select district first',
    'pitches.pitchPrice': 'Price',
    'pitches.selectPitchFirst': 'Select pitch first',
    'pitches.locationPermissionRequired': 'Location permission required',
    'pitches.locationPermissionMessage': 'You need to grant location permission to use the app.',
    'pitches.addressNotFound': 'Address not found.',
    'pitches.addressCouldNotBeRetrieved': 'Address could not be retrieved.',
    'pitches.locationCouldNotBeRetrieved': 'Location could not be retrieved.',
    'pitches.locationError': 'Location Error',
    'pitches.locationInfoCouldNotBeRetrieved': 'Location information could not be retrieved.',
    'pitches.permissionCheckError': 'Permission check error',
    'pitches.dataFetchError': 'Data fetch error',
    'pitches.listPitchesByLocation': 'List Pitches by Your Location',
    'pitches.yourAddress': 'Your Address',
    'pitches.findYourLocation': 'Find Your Location',
    'pitches.pitchSummary': 'PITCH SUMMARY',
    'pitches.openAddress': 'Open Address',
    'pitches.pitchFeatures': 'Pitch Features',
    
    // Messages
    'messages.title': 'Messages',
    'messages.noAcceptedJoins': 'No accepted joins yet',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.loadingError': 'Error loading notifications',
    'notifications.followRequestError': 'Error processing follow request',
    'notifications.sentFollowRequest': 'sent you a follow request.',
    'notifications.sentMessage': 'sent you a message.',
    'notifications.noNotificationsYet': 'You have no notifications yet',
    'notifications.userFallback': 'User',
    'notifications.toast.accepted': 'Request accepted',
    'notifications.toast.rejected': 'Request rejected',
    'notifications.actionCompleted': 'Action completed',

    // Follow request feedbacks (follow_request)
    'notifications.follow.startedFollowing': '{name} started following you.',
    'notifications.follow.acceptedYourRequest': '{name} accepted your follow request.',
    'notifications.follow.rejectedYourRequest': '{name} rejected your follow request.',
    'notifications.follow.youRejectedRequest': "You rejected {name}'s follow request.",
    
    // General
    'general.close': 'Close',
    'general.cancel': 'Cancel',
    'general.save': 'Save',
    'general.edit': 'Edit',
    'general.delete': 'Delete',
    'general.yes': 'Yes',
    'general.no': 'No',
    'general.ok': 'OK',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.loading': 'Loading...',
    'general.back': 'Back',
    'general.notifications': 'Notifications',
    'general.notificationCount': 'Notification Count',
    'general.reject': 'Reject',
    'general.accept': 'Accept',
    'general.sendMessage': 'Send Message',
    
    // Language Settings
    'language.settings': 'Language Settings',
    'language.turkish': 'Turkish',
    'language.english': 'English',
    'language.changed': 'Language changed',
    'language.changedToTurkish': 'Language set to Turkish',
    'language.changedToEnglish': 'Language set to English',
    'language.changeFailed': 'Language could not be changed',

    // Settings Modal
    'settings.invalidEmail': 'Please enter a valid email address.',
    'settings.emailUpdateRequestedVerifyInbox': 'Email change request received. Please check your inbox and complete the verification step.',
    'settings.emailUpdatedMaybeVerify': 'Email updated. If verification is required, you may have received a confirmation email.',
    'settings.emailUpdateFailed': 'Email could not be updated. Please try again.',
    'settings.passwordMin': 'Password must be at least 6 characters.',
    'settings.passwordsMismatch': 'Passwords do not match.',
    'settings.passwordUpdated': 'Password updated.',
    'settings.passwordUpdateFailed': 'Password could not be updated. Please try again.',
    'settings.accountDeleted': 'Your account has been deleted.',
    'settings.accountDeleteFailed': 'Account could not be deleted. Please try again or contact support.',

    'settings.delete.title': 'Delete Account',
    'settings.delete.description': 'If you delete your account, your profile, messages, notifications, and other data will be permanently removed.',
    'settings.delete.irreversible': 'This action cannot be undone.',
    'settings.delete.confirmQuestion': 'Do you want to continue?',
    'settings.delete.confirmButton': 'Yes, delete',

    'settings.account.title': 'My Account Info',
    'settings.account.emailLabel': 'Email',
    'settings.account.passwordLabel': 'Password',
    'settings.account.passwordHiddenNote': 'Password is not shown for security reasons.',
    'settings.account.updateEmail': 'Update Email',
    'settings.account.changePassword': 'Change Password',
    'settings.account.newEmailLabel': 'New Email',
    'settings.account.emailPlaceholder': 'example@mail.com',
    'settings.account.emailVerifyNote': 'Note: Email change may require verification.',
    'settings.account.newPasswordLabel': 'New Password',
    'settings.account.newPasswordConfirmLabel': 'New Password (Confirm)',

    'settings.device.title': 'Device Info',
    'settings.device.appInfoTitle': 'App Info',
    'settings.device.appLabel': 'App',
    'settings.device.versionLabel': 'Version',
    'settings.device.deviceLabel': 'Device',
    'settings.device.osLabel': 'Operating System',
    'settings.device.updateStatusLabel': 'Update Status',
    'settings.device.updateNotSupported': 'Not supported on this device',
    'settings.device.updateChecking': 'Checking...',
    'settings.device.updateCheckFailed': 'Could not check',
    'settings.device.updateAvailable': 'Update available',
    'settings.device.upToDate': 'Up to date',
    'settings.device.unknown': 'Unknown',
    'settings.device.goToStore': 'Go to App Store',

    // Auth (Sign in / Sign up)
    'auth.slide1.title': 'Find Match',
    'auth.slide1.subtitle': 'Join nearby matches and play with new people.',
    'auth.slide2.title': 'Create Match',
    'auth.slide2.subtitle': 'Pick a pitch, set the time, build your squad.',
    'auth.slide3.title': 'Manage Squad',
    'auth.slide3.subtitle': 'Set missing positions and manage requests.',
    'auth.slide4.title': 'Chat',
    'auth.slide4.subtitle': 'Message your teammates and opponents.',
    'auth.slide5.title': 'Complete Profile',
    'auth.slide5.subtitle': 'Introduce yourself and get better matches.',
    'auth.slide6.title': 'Complete Profile',
    'auth.slide6.subtitle': 'Introduce yourself and get better matches.',

    'auth.welcomeTitle': 'Welcome',
    'auth.joinTitle': 'Join Us!',
    'auth.brand': "P I T C H'E  B A K",
    'auth.subtitleLoginPrefix': 'To get on the pitch,',
    'auth.subtitleLoginAction': 'sign in',
    'auth.subtitleSignup': 'Create a new account',

    'auth.emailPlaceholder': 'Your email',
    'auth.passwordPlaceholder': 'Your password',
    'auth.signInButton': 'Sign In',
    'auth.signUpButton': 'Sign Up',

    'auth.noAccountQuestion': "Don't have an account?",
    'auth.signUpLink': 'Sign up',
    'auth.haveAccountQuestion': 'Already have an account?',
    'auth.signInLink': 'Sign in',
    'auth.or': 'or',
    'auth.googleSignIn': 'Sign in with Google',
    'auth.appleSignIn': 'Sign in with Apple',
    'auth.completeProfileNote': 'After signing in, you can complete your profile.',

    'auth.userCreateFailed': "Couldn't create user record. Please try again.",
    'auth.unknownError': 'Unknown error',
    'auth.fillAllFields': 'Please fill in all fields.',
    'auth.invalidEmail': 'Invalid email format.',
    'auth.passwordMin': 'Password must be at least 6 characters.',
    'auth.signupSuccessVerifyEmail': 'Sign-up successful! Please verify your email address. Check your inbox to confirm your email.',
    'auth.signInCancelled': 'Sign-in cancelled.',
    'auth.userInfoMissing': "Couldn't retrieve user information.",
    'auth.appleAuthFailed': 'Apple authentication failed (could not get token).',

    'auth.errors.passwordMin': 'Password must be at least 6 characters.',
    'auth.errors.invalidEmail': 'Invalid email format.',
    'auth.errors.userAlreadyRegistered': 'A user with this email is already registered.',
    'auth.errors.userAlreadyExists': 'An account with this email already exists.',
    'auth.errors.invalidCredentials': 'Email or password is incorrect.',
    'auth.errors.emailNotConfirmed': 'You need to confirm your email address.',
    'auth.errors.userNotFound': 'User not found.',
    'auth.errors.appleMissingOAuthSecret': "Apple sign-in isn't configured: missing OAuth client secret in Supabase (Auth → Providers → Apple).",
    'auth.errors.missingOAuthSecret': "OAuth isn't configured: missing client secret in Supabase (Auth → Providers).",
    
    // Match
    'match.createSuccess': 'Congratulations 🎉\nYour match has been created successfully.',
    'match.createError': 'An error occurred while creating the match. Please try again.',
    'match.title': 'Match Title',
    'match.date': 'Date',
    'match.time': 'Time',
    'match.location': 'Location',
    'match.price': 'Price',
    'match.players': 'Players',
    'match.selectDate': 'Select Date',
    'match.selectTime': 'Select Time',
    'match.today': 'Today',
    'match.tomorrow': 'Tomorrow',
    'match.thisWeek': 'This Week',
    'match.nextWeek': 'Next Week',
    'match.morning': 'Morning',
    'match.afternoon': 'Afternoon',
    'match.evening': 'Evening',
    'match.night': 'Night',
    'dateFormat.day': 'Day',
    'dateFormat.month': 'Month',
    'dateFormat.year': 'Year',
    'dateFormat.today': 'Today',
    'dateFormat.tomorrow': 'Tomorrow',
    'dateFormat.thisWeek': 'This Week',
    'dateFormat.nextWeek': 'Next Week',
  }
};

// Dil context provider
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('tr');

  // Uygulama başladığında kaydedilen dili yükle
  useEffect(() => {
    loadSavedLanguage();
  }, []);

  // Kaydedilen dili yükle
  const loadSavedLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem('selectedLanguage');
      if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
        setCurrentLanguage(savedLanguage as Language);
      }
    } catch (error) {
      // Sessizce varsayılan dilde kal
      console.log('Dil yüklenirken hata (varsayılan kullanılacak):', error);
    }
  };

  // Dili değiştir
  const changeLanguage = async (language: Language) => {
    try {
      await AsyncStorage.setItem('selectedLanguage', language);
      setCurrentLanguage(language);
    } catch (error) {
      console.error('Dil değiştirilirken hata:', error);
      throw error;
    }
  };

  // Çeviri fonksiyonu
  const t = (key: string): string => {
    const translation = translations[currentLanguage][key as keyof typeof translations[typeof currentLanguage]];
    if (!translation) {
      console.warn(`Translation key not found: ${key}`);
      return key;
    }
    return translation;
  };

  const value: LanguageContextType = {
    currentLanguage,
    changeLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Dil context hook'u
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
